image: mcr.microsoft.com/dotnet/sdk:7.0

stages:          # List of stages for jobs, and their order of execution
  - build
  - test

before_script:
  - dotnet --version

build_model:       # This job runs in the build stage, which runs first.
  stage: build
  script:
    - dotnet build projects/BomberWars_MP
    - dotnet build projects/BomberWars

build_view:
  stage: build
  image: mcr.microsoft.com/dotnet/sdk:7.0.407-windowsservercore-ltsc2019
  tags: [windows]
  script:
    - dotnet build projects/BomberWars/BomberWars.sln

unit-test-job:   # This job runs in the test stage.
  stage: test    # It only starts when the job in the build stage completes successfully.
  script:
    - dotnet test projects/UnitTests
